In [45]:
import tensorflow as tf
import numpy as np

In [46]:
a = tf.constant([[[1,2],[2,1],[3,3]], [[1,2],[2,3],[3,4]]])
print(a)
b = tf.transpose(tf.random.shuffle(tf.transpose(a)))
print(b)

tf.Tensor(
[[[1 2]
  [2 1]
  [3 3]]

 [[1 2]
  [2 3]
  [3 4]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [2 1]
  [3 3]]

 [[1 2]
  [2 3]
  [3 4]]], shape=(2, 3, 2), dtype=int32)


In [41]:
a2 = np.random.randint(5, size=(2, 2, 4, 3 ))

In [42]:
a2

array([[[[3, 0, 4],
         [2, 1, 4],
         [1, 0, 1],
         [3, 3, 2]],

        [[4, 3, 0],
         [3, 4, 1],
         [2, 3, 3],
         [0, 1, 0]]],


       [[[0, 3, 2],
         [4, 3, 3],
         [2, 3, 2],
         [4, 1, 1]],

        [[4, 2, 1],
         [1, 3, 3],
         [3, 3, 4],
         [4, 0, 3]]]])

In [44]:
a2[:, :, :, [2, 1, 0]]

array([[[[4, 0, 3],
         [4, 1, 2],
         [1, 0, 1],
         [2, 3, 3]],

        [[0, 3, 4],
         [1, 4, 3],
         [3, 3, 2],
         [0, 1, 0]]],


       [[[2, 3, 0],
         [3, 3, 4],
         [2, 3, 2],
         [1, 1, 4]],

        [[1, 2, 4],
         [3, 3, 1],
         [4, 3, 3],
         [3, 0, 4]]]])